export declare const getwayBaseUrl = "http://gateway:8080";
export declare const imServerBaseUrl = "http://im-gateway:8080";
export declare const vpnServerBaseUrl = "http://vpn-gateway:8080";
export declare const uatServerBaseUrl = "http://bff-330056:4100/api/forward/";
export declare const getBaseServerUrl: (bid: string | number) => string;
export declare const commonServerBaseUrl = "http://bff:4100/api/forward/";
export declare const coreServerBaseUrl = "http://bff.core:4100/api/forward/";
export declare const s3AndOssDefaultConfig: {
    originS3Domain: string;
    fastS3Domain: string;
    fastS3DomainOld: string;
    originOSSDomain: string;
    fastOSSDomain: string;
    originOSSDomainOld: string;
    fastOSSDomainOld: string;
    originDevS3ProdUploadDomain: string;
    fastDevS3ProdUploadDomain: string;
    originDevS3DevUploadDomain: string;
    fastDevS3DevUploadDomain: string;
    mergeModeS3ProdDomain: string;
    mergeModeS3TestDomain: string;
    mergeModeS3DevDomain: string;
};
export declare const s3ProdConfig: {
    originProdS3Domain: string;
    fastProdS3Domain: string;
};
export declare const s3StagingConfig: {
    originTestS3Domain: string;
    fastTestS3Domain: string;
};
export declare const s3DevConfig: {
    originDevS3Domain: string;
    fastDevS3Domain: string;
};
export declare const s3CommonConfig: {
    originDevS3Domain: string;
    fastDevS3Domain: string;
    originTestS3Domain: string;
    fastTestS3Domain: string;
    originProdS3Domain: string;
    fastProdS3Domain: string;
    originS3Domain: string;
    fastS3Domain: string;
    fastS3DomainOld: string;
    originOSSDomain: string;
    fastOSSDomain: string;
    originOSSDomainOld: string;
    fastOSSDomainOld: string;
    originDevS3ProdUploadDomain: string;
    fastDevS3ProdUploadDomain: string;
    originDevS3DevUploadDomain: string;
    fastDevS3DevUploadDomain: string;
    mergeModeS3ProdDomain: string;
    mergeModeS3TestDomain: string;
    mergeModeS3DevDomain: string;
};
export declare const s3UatConfig: {
    originProdS3Domain: string;
    fastProdS3Domain: string;
    originDevS3Domain: string;
    fastDevS3Domain: string;
    originTestS3Domain: string;
    fastTestS3Domain: string;
    originS3Domain: string;
    fastS3Domain: string;
    fastS3DomainOld: string;
    originOSSDomain: string;
    fastOSSDomain: string;
    originOSSDomainOld: string;
    fastOSSDomainOld: string;
    originDevS3ProdUploadDomain: string;
    fastDevS3ProdUploadDomain: string;
    originDevS3DevUploadDomain: string;
    fastDevS3DevUploadDomain: string;
    mergeModeS3ProdDomain: string;
    mergeModeS3TestDomain: string;
    mergeModeS3DevDomain: string;
};
